# library(testthat); library(downsize)
context("scaling")

test_that("Deprecated scaling functions run correctly", suppressWarnings({
  scale_down()
  expect_equal(scaling(), "scaled down")
  scale_up()
  expect_equal(scaling(), "scaled up")

  scale_down()
  library(downsize)
  expect_equal(scaling(), "scaled down")

  scale_up()
  library(downsize)
  expect_equal(scaling(), "scaled up")

  scale_down()
  expect_equal(scaling(), "scaled down")
  expect_equal(scaling(), "scaled down")
  scale_up()
  expect_equal(scaling(), "scaled up")
  expect_equal(scaling(), "scaled up")

  scale_down()
  scale_down()
  expect_equal(scaling(), "scaled down")
  scale_up()
  scale_up()
  expect_equal(scaling(), "scaled up")

  scale_down()
  scale_up()
  scale_down()
  expect_equal(scaling(), "scaled down")
  scale_up()
  scale_down()
  scale_up()
  expect_equal(scaling(), "scaled up")
}))
