# library(testthat); library(downsize)
context("ds_array")

test_that("Function ds_array runs correctly", {
  a = matrix(1:120, ncol = 10)
  dim = c(10, 3, 100, 7, 12)
  b = array(1:prod(dim), dim = dim)

  expect_equal(ds_array(a), a)
  expect_error(ds_array(a, dim = 1))  
  expect_equal(ds_array(a, dim = 1:2), matrix(a[1,1:2], nrow = 1))  
  expect_equal(ds_array(a, dim = 2:1), matrix(a[1:2, 1], ncol = 1))  
  expect_equal(ds_array(a, dim = 3:4), a[1:3,1:4])  
  set.seed(0)
  x = ds_array(a, dim = 2:3, random = T)
  expect_equal(dim(x), 2:3)
  expect_false(all(x == a[1:2, 1:3]))

  expect_equal(ds_array(b), b)
  expect_error(ds_array(b, dim = 1))  
  expect_equal(ds_array(b, dim = 1:5), array(b[1,1:2,1:3,1:4,1:5], dim = 1:5))  
  expect_equal(ds_array(b, dim = 2:6), b[1:2,1:3,1:4,1:5,1:6])  
  set.seed(0)
  x = ds_array(b, dim = 2:6, random = T)
  expect_equal(dim(x), 2:6)
  expect_false(all(x == b[1:2, 1:3, 1:4, 1:5, 1:6]))
})
