# library(testthat); library(downsize)
context("downsize")

test_that("Function ds runs correctly", {
  a = matrix(1:100, ncol = 10)
  b = array(0, dim = c(10, 2, 100, 2, 12))

  options(downsize = TRUE)
  expect_error(ds())
  expect_equal("bob", ds("jim", "bob"))
  expect_equal("jim", ds(c("jim", "bob"), length = 1))
  expect_equal(a[,1:2], ds(a, ncol = 2))
  expect_equal(a[1:2,], ds(a, nrow = 2))
  expect_equal(a[1:2,1:3], ds(a, nrow = 2, dim = c(3,3)))
  expect_equal(a[1:3,1:2], ds(a, ncol = 2, dim = c(3,3)))
  expect_equal(b[1:3, 1:2, 1:3, 1:2, 1:3], ds(b, dim = c(3,3,3,3,3)))
  expect_equal(b[1:9, 1:2, 1:3, 1:2, 1:3], ds(b, nrow = 9, dim = c(3,3,3,3,3)))

  options(downsize = FALSE)
  expect_error(ds())
  expect_equal("jim", ds("jim", "bob"))
  expect_equal(c("jim", "bob"), ds(c("jim", "bob"), length = 1))
  expect_equal(a, ds(a, ncol = 2))
  expect_equal(a, ds(a, nrow = 2))
  expect_equal(a, ds(a, dim = c(3, 3)))
  expect_equal(b, ds(b, dim = c(3,3,3,3,3)))
  expect_equal(b, ds(b, nrow = 9, dim = c(3,3,3,3,3)))
})
