# library(testthat); library(downsize)
context("downsize")

test_that("Function ds runs correctly", {
  a = matrix(1:100, ncol = 10)
  b = array(0, dim = c(10, 2, 100, 2, 12))
  l = list(a = 0, b = 1, c = list(a = 0, b = 1))
  data(mtcars)

  expect_equal("jim", ds("jim", "bob", downsize = F))
  expect_equal("bob", ds("jim", "bob", downsize = T))

  scale_down()
  expect_error(ds())
  expect_equal(mtcars[1:5,], ds(mtcars, nrow = 5))
  expect_equal(mtcars[,1:5], ds(mtcars, ncol = 5))
  expect_equal(mtcars[1:3, 1:5], ds(mtcars, nrow = 3, ncol = 5))
  expect_equal(mtcars[1:3, 1:5], ds(mtcars, dim = c(3, 5)))
  expect_equal("bob", ds("jim", "bob"))
  expect_equal("jim", ds(c("jim", "bob"), length = 1))
  expect_equal(a[,1:2], ds(a, ncol = 2))
  expect_equal(a[1:2,], ds(a, nrow = 2))
  expect_equal(a[1:2,1:3], ds(a, nrow = 2, ncol = 3))
  expect_equal(a[1:2,1:3], ds(a, nrow = 2, dim = c(3,3)))
  expect_equal(a[1:3,1:2], ds(a, ncol = 2, dim = c(3,3)))
  expect_equal(b[1:3, 1:2, 1:3, 1:2, 1:3], ds(b, dim = c(3,3,3,3,3)))
  expect_equal(b[1:9, 1:2, 1:3, 1:2, 1:3], ds(b, nrow = 9, dim = c(3,3,3,3,3)))
  expect_equal(ds(a, "hi"), "hi")
  expect_equal(ds(a, "hi", length = 4), "hi")
  expect_equal(ds(a, "hi", dim = 1:2), "hi") 
  expect_equal(ds(a, "hi", nrow = 5), "hi")
  expect_equal(ds(l), l)
  expect_equal(ds(l, small = "hi"), "hi")
  expect_equal(ds(l, length = 1), l)
  expect_equal(ds(l, dim = 1), l)
  expect_equal(ds(l, dim = 2:3), l)
  expect_equal(ds(l, nrow = 2), l)
  expect_equal(ds(l, ncol = 4), l)
  expect_equal(ds(l, nrow = 2, ncol = 4), l)

  scale_up()
  expect_error(ds())
  expect_equal(mtcars, ds(mtcars, nrow = 5))
  expect_equal(mtcars, ds(mtcars, ncol = 5))
  expect_equal(mtcars, ds(mtcars, nrow = 3, ncol = 5))
  expect_equal(mtcars, ds(mtcars, dim = c(3, 5)))
  expect_equal("jim", ds("jim", "bob"))
  expect_equal(c("jim", "bob"), ds(c("jim", "bob"), length = 1))
  expect_equal(a, ds(a, ncol = 2))
  expect_equal(a, ds(a, nrow = 2))
  expect_equal(a, ds(a, dim = c(3, 3)))
  expect_equal(b, ds(b, dim = c(3,3,3,3,3)))
  expect_equal(b, ds(b, nrow = 9, dim = c(3,3,3,3,3)))
  expect_equal(ds(a, "hi", length = 4), a)
  expect_equal(ds(a, "hi", dim = 1:2), a) 
  expect_equal(ds(a, "hi", nrow = 5), a)
  expect_equal(ds(l), l)
  expect_equal(ds(l, small = "hi"), l)
  expect_equal(ds(l, length = 1), l)
  expect_equal(ds(l, dim = 1), l)
  expect_equal(ds(l, dim = 2:3), l)
  expect_equal(ds(l, nrow = 2), l)
  expect_equal(ds(l, ncol = 4), l)
  expect_equal(ds(l, nrow = 2, ncol = 4), l)
})
